### ISSUE TITLE
postgress-docker-compose

### ISSUE THREAD

**Issue by live-dev999** [O2-Bionics/O2NextGen#185]
```
version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: publicis-usage-tracking
        POSTGRES_USER: root
        POSTGRES_PASSWORD: G9Wd2689
        PGDATA: /tmp
    
    networks:
      - backend

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
    networks:
      - backend

volumes:
  db_volume:

networks:
  backend:
```

[AB#57](https://dev.azure.com/o2-bionics-llc/cda9516b-08ff-4491-bc59-836494579e0d/_workitems/edit/57)
